version: '3.8'

services:
  prayer_times_wallpaper-app:
    image: ardax/prayer-times-wallpaper:latest
    ports:
      - "5164:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
